
from flask import Flask, render_template,redirect, url_for
from flask_wtf import FlaskForm
import joblib
from wtforms import StringField, RadioField, SelectField,SubmitField
from wtforms.validators import DataRequired

app=Flask(__name__)
app.config['SECRET_KEY']='key'

class InfoForm(FlaskForm):
 Make = SelectField('Select Car Make',choices=[('Skoda','Skoda'), ('Proton','Proton'),('Suzuki','Suzuki'),
 ('Peugeot','Peugeot'),('Citro�n','Citro�n'),('MG','MG'),('Nissan','Nissan'),('Renault','Renault'),('Chevrolet','Chevrolet'),
 ('Fiat','Fiat'),('Kia','Kia'),('Daewoo','Daewoo'),('Opel','Opel'),('Changan','Changan'),('Hyundai','Hyundai'),('Jeep','Jeep'),
 ('BMW','BMW'),('Toyota','Toyota'),('Seat','Seat'),('Subaru','Subaru'),('Porsche','Porsche'),('Mercedes','Mercedes'),
 ('Mitsubishi','Mitsubishi'),('Volkswagen','Volkswagen'),('Honda','Honda'),('Byd','Byd'),('Dodge','Dodge'),('Audi','Audi')
,('Geely','Geely'),('Lada','Lada'),('Speranza','Speranza'),('Emgrand','Emgrand'),('Land Rover','Land Rover'),('Chery','Chery'),
 ('Jac','Jac'),('Mazda','Mazda'),('Brilliance','Brilliance'),('Mini','Mini'),('Infiniti','Infiniti'),('Senova','Senova'),('Ford','Ford'),
 ('Isuzu','Isuzu'),('Daihatsu','Daihatsu'),('DFSK','DFSK'),('Ssang Yong','Ssang Yong'),('Kenbo','Kenbo'),('Faw','Faw'),('Ds','Ds'),
 ('Volvo','Volvo'),('Zotye','Zotye'),('Chrysler','Chrysler'),('Jaguar','Jaguar'),('Haval','Haval'),('Alfa Romeo','Alfa Romeo'),
 ('Mahindra','Mahindra'),('Great Wall','Great Wall'),('Bentley','Bentley'),('Jetour','Jetour'),('Canghe || Changhe','Canghe || Changhe'),
 ('Saipa','Saipa'),('Lancia','Lancia'),('Karry','Karry'),('Haima','Haima'),('Baic','Baic'),('Soueast','Soueast'),('Chana','Chana'),
 ('Lexus','Lexus'),('Sokon','Sokon'),('Lifan','Lifan'),('Hafei','Hafei'),('Keyton','Keyton'),('Hawtai','Hawtai'),('Datsun','Datsun'),
 ('Hummer','Hummer'),('Cadillac','Cadillac'),('Jonway','Jonway'),('Buick','Buick'),('Domy','Domy'),('Ferrari','Ferrari')
,('Maserati','Maserati'),('Landwind','Landwind'),('Gmc','Gmc'),('Tesla','Tesla'),('Pontiac','Pontiac'),('DFM','DFM'),
('Bugatti','Bugatti'),('Tata','Tata'),('Foton','Foton')

 ])
 Model = SelectField('Select Car Model',choices=[('Octavia A4','Octavia A4'),('Preve','Preve'),('Maruti','Maruti'),('508','508'),
 ('C4 Picasso','C4 Picasso'),('ZS','ZS'),
 ('Sunny','Sunny'),('Sandero Step Way','Sandero Step Way'),('Lanos','Lanos'),('Punto','Punto'),('Cerato','Cerato'),
 ('Logan','Logan'),('Corsa','Corsa'),('Felicia','Felicia'),('CS 35','CS 35'),('127','127'),('Elantra HD','Elantra HD'),
 ('Optra','Optra'),('Liberty','Liberty'),('Aveo','Aveo'),('528','528'),('Qashqai','Qashqai'),
 ('Corolla','Corolla'),('Yaris','Yaris'),('405','405'),('316','316'),('Leon','Leon'),('Cruze','Cruze'),('Accent','Accent'),
 ('Soul','Soul'),('Swift','Swift'),('320','320'),('Gen 2','Gen 2'),('Toledo','Toledo'),('XV','XV'),('Macan','Macan'),
 ('Verna','Verna'),('Fantasia','Fantasia'),
 ('C 180','C 180'),('Grand Cerato','Grand Cerato'),('Regata','Regata'),('124','124'),('Elantra CN7','Elantra CN7'),('GLA','GLA')
 ,('Nubira 2','Nubira 2'),('Lancer','Lancer'),('Juliet','Juliet'),('Shahin','Shahin'),('Passat','Passat'),('Elantra AD','Elantra AD')
 ,('HRV','HRV'),('E 350','E 350'),('Veloster','Veloster'),('CLA 200','CLA 200'),
 ('Tucson Turbo GDI || Tucson Turbo','Tucson Turbo GDI || Tucson Turbo'),('F3','F3'),('Golf','Golf'),('X3','X3'),
 ('Picanto','Picanto'),('Scala','Scala'),('132','132'),('Carnival','Carnival'),('128','128'),('Polonez','Polonez'),('Vectra','Vectra')
 ,('Dart','Dart'),('Q5','Q5'),('Grandland','Grandland'),('Imperial','Imperial'),('504','504'),
 ('Octavia A7','Octavia A7'),('Grand Cherokee','Grand Cherokee'),('Sephia','Sephia'),('C5','C5'),('C5 Aircross','C5 Aircross'),
 ('Rio','Rio'),('Kodiaq','Kodiaq'),('Jetta','Jetta'),('Astra','Astra'),('C4','C4'),('2107','2107'),('Clio','Clio'),('Sentra','Sentra'),
 ('Emgrand 7','Emgrand 7'),('Saga','Saga'),('Tiggo','Tiggo'),
 ('S Presso','S Presso'),('Accent RB','Accent RB'),('500','500'),('9','9'),('Getz','Getz'),('Duster','Duster'),
 ('Tucson GDI','Tucson GDI'),('C 200','C 200'),('B 180','B 180'),('Tipo','Tipo'),('Elantra','Elantra'),('Attrage','Attrage'),
 ('Uno','Uno'),('Xpander','Xpander'),('Elantra MD','Elantra MD'),('C 240','C 240'),
 ('Kadjar','Kadjar'),('C Elysee','C Elysee'),('Excel','Excel'),('Q7','Q7'),('Berlingo','Berlingo'),('C 250','C 250'),
 ('Spark','Spark'),('City','City'),('Lanos 2','Lanos 2'),('Sportage','Sportage'),('EC 7','EC 7'),
 ('Range Rover Vogue || Vogue','Range Rover Vogue || Vogue'),('IX 35','IX 35'),('Waja','Waja'),('Swift Dzire || Dzire','Swift Dzire || Dzire'),
 ('Arrizo 5','Arrizo 5'),
 ('Koup','Koup'),('Megane','Megane'),('HS','HS'),('A113','A113'),('6','6'),('Octavia A8','Octavia A8'),('Envy','Envy'),
 ('S7','S7'),('Fluence','Fluence'),('A516','A516'),('218 i','218 i'),('',''),('',''),('',''),('',''),('',''),
 ('Vitara','Vitara'),('929','929'),('V6','V6'),('Matrix','Matrix'),('Pickup','Pickup'),('Polo','Polo'),
 ('Range Rover Evoque || Evoque','Range Rover Evoque || Evoque'),('Crossland','Crossland'),('406','406'),('Granta','Granta'),
 ('Pegas','Pegas'),('Atos','Atos'),('C3 Aircross','C3 Aircross'),('Sandero','Sandero'),('Cooper','Cooper'),('1100','1100'),
 ('3008','3008'),('Q30','Q30'),('408','408'),('A 200','A 200'),('Octavia','Octavia'),('740','740'),('Insignia','Insignia'),
 ('N300','N300'),('A1','A1'),('CLA 250','CLA 250'),('Avante','Avante'),('Captur','Captur'),('Pride','Pride'),('Nubira 1','Nubira 1'),
 ('Benni','Benni'),('A11','A11'),
 ('Captiva','Captiva'),('Samara','Samara'),('Sonic','Sonic'),('Van','Van'),('Wrangler','Wrangler'),('Tucson','Tucson'),('Ibiza','Ibiza')
 ,('GLK','GLK'),('Civic','Civic'),('1200','1200'),('Ceed','Ceed'),('307','307'),('Mondeo','Mondeo'),('I30','I30'),('Shuma','Shuma')
 ,('D max','D max'),
 ('A3','A3'),('1500','1500'),('Tiguan','Tiguan'),('FRV Cross','FRV Cross'),('318','318'),('3 || Mazda 3','3 || Mazda 3'),
 ('Terios','Terios'),('T-Series','T-Series'),('12','12'),('Tigra','Tigra'),('Juke','Juke'),('Wrangler Unlimited','Wrangler Unlimited'),
 ('Venture','Venture'),('V5','V5'),('Fiesta','Fiesta'),('330S','330S'),
 ('Tivoli XLV','Tivoli XLV'),('Minivan','Minivan'),('330','330'),('Carens','Carens'),('Q3','Q3'),('Octavia A5','Octavia A5')
 ,('131','131'),('Meriva','Meriva'),('Besturn','Besturn'),('X1','X1'),('525','525'),('M5','M5'),('180','180'),('Belta','Belta'),
 ('Galena','Galena'),('Siena','Siena'),
 ('Equinox','Equinox'),('Wira','Wira'),('301','301'),('230','230'),('Tempra','Tempra'),('DS7','DS7'),('2105','2105'),('5','5')
 ,('Ertiga','Ertiga'),('Solaris','Solaris'),('Superb','Superb'),('Escort','Escort'),('Petra','Petra'),('Pick up','Pick up'),
 ('Tiida','Tiida'),('Brava','Brava'),
 ('C3','C3'),('Z4','Z4'),('Accent HCI','Accent HCI'),('I10','I10'),('Fortuner','Fortuner'),('Lacetti','Lacetti'),('Hilux','Hilux'),
 ('Rx5','Rx5'),('S40','S40'),('Pointer','Pointer'),('Jimny','Jimny'),('Tivoli','Tivoli'),('Alto','Alto'),('Renegade','Renegade'),
 ('XC60','XC60'),('S80','S80'),
 ('Cherokee','Cherokee'),
 ('GL Class','GL Class'),('E 300','E 300'),('FRV','FRV'),('Echo','Echo'),('2 || Mazda 2','2 || Mazda 2'),('Spectra','Spectra')
 ,('200','200'),('205','205'),('Range Rover','Range Rover'),('Xplosion','Xplosion'),('323','323'),('J7','J7'),
 ('EAGLE 580','EAGLE 580'),('18','18'),('Ck2','Ck2'),('E 180','E 180'),
 ('Prado','Prado'),('Niva','Niva'),('Kancil','Kancil'),('523','523'),('E 200','E 200'),('Persona','Persona'),('Dogan','Dogan'),
 ('Lumina','Lumina'),('X6','X6'),('Scenic','Scenic'),('240','240'),('S60','S60'),('Cordoba','Cordoba'),('206','206')
 ,('Emgrand X7','Emgrand X7'),('Outlander','Outlander'),
  ('Tiggo 3','Tiggo 3'),('Town & Country','Town & Country'),('H530','H530'),('Leganza','Leganza'),('X-Type','X-Type'),('Palio','Palio')
  ,('2017','2017'),('Eclipse','Eclipse'),('Range Rover Sport || Sport','Range Rover Sport || Sport'),
  ('308','308'),('Forte','Forte'),('Mira','Mira'),('X4','X4'),('Pajero','Pajero'),('F-Pace','F-Pace'),('N200','N200'),
 ('L3','L3'),('Xceed','Xceed'),('Gran max','Gran max'),('Creta','Creta'),('Glory 330','Glory 330'),('Velar','Velar'),
 ('GLK 350','GLK 350'),('Pandino','Pandino'),('SEL 500','SEL 500'),('Z300','Z300'),('ML','ML'),('Eclipse Cross','Eclipse Cross'),
 ('Avanza','Avanza'),('Ciaz','Ciaz'),('Focus','Focus'),('M12','M12'),
 ('Kuga','Kuga'),('520','520'),('Bora','Bora'),('E 240','E 240'),('E 250','E 250'),('Viva','Viva'),('X5','X5'),('T600','T600')
 ,('1300','1300'),('350','350'),('Jolion','Jolion'),('2008','2008'),('156','156'),('SIRION','SIRION'),('ZX','ZX'),('Fruits','Fruits'),
 ('Scorpio','Scorpio'),('Tercel','Tercel'),('S2','S2'),('DS5','DS5'),('C30','C30'),('RCZ','RCZ'),('E 220','E 220'),
 ('Defender','Defender'),('Matiz','Matiz'),('Mini Cooper S','Mini Cooper S'),('Rapid Spaceback','Rapid Spaceback'),
 ('Azure','Azure'),('Ix20','Ix20'),('X70','X70'),('B 150','B 150'),('Ritmo','Ritmo'),
  ('Argenta','Argenta'),('Ax','Ax'),('Impreza','Impreza'),('Turan','Turan'),('E 280','E 280'),('Maple','Maple'),('Charade','Charade')
  ,('M50 || M 50','M50 || M 50'),('Splendor','Splendor'),('Ck','Ck'),('244','244'),('Land Cruiser','Land Cruiser'),('JS3','JS3'),
  ('Komodo','Komodo'),('CC','CC'),('B 160','B 160'),
  ('304','304'),('Optima','Optima'),('Mito','Mito'),('Vita','Vita'),('505','505'),('530','530'),('GLA 180','GLA 180'),
  ('Fusion','Fusion'),('John Cooper','John Cooper'),('CLS Class','CLS Class'),('Doblo','Doblo'),('M11','M11'),('Corona','Corona')
  ,('FSV','FSV'),('Armada','Armada'),('Malibu','Malibu'),
  ('Favorit','Favorit'),('E 200 AMG','E 200 AMG'),('Saipa','Saipa'),('Delta','Delta'),('Florid','Florid'),('SEL 350','SEL 350'),
  ('Arrizo 3','Arrizo 3'),('S 560','S 560'),('Tiggo 7 pro','Tiggo 7 pro'),('3','3'),('B 200','B 200'),('S4','S4'),('XTrail || XTrail','XTrail || XTrail'),
  ('Yeti','Yeti'),('Rainbow','Rainbow'),('N-Series','N-Series'),
  ('Caprice','Caprice'),('S5','S5'),('Punto evo','Punto evo'),('Grand C-Max','Grand C-Max'),('Q22','Q22'),('5008','5008'),('Sorento','Sorento')
  ,('Livina','Livina'),('A213','A213'),('GLC 200','GLC 200'),('Santamo','Santamo'),('S3','S3'),('133','133'),('X40','X40'),('Fabia','Fabia'),('',''),
  ('Mokka','Mokka'),('Colt','Colt'),('M3','M3'),('Carina','Carina'),('ideal || Ideal','ideal || Ideal'),('Felicia combi','Felicia combi')
  ,('Zaz','Zaz'),('125','125'),('207','207'),('650','650'),('Giulietta','Giulietta'),('Murano','Murano'),('H1','H1'),
  ('Grand terios','Grand terios'),('Xsara','Xsara'),('Parati','Parati'),
  ('518','518'),('Espero','Espero'),('Spark Lite','Spark Lite'),('Accord','Accord'),('A620 || A620 ','A620 || A620 ')
  ,('XC90','XC90'),('Corolla Cross','Corolla Cross'),('80','80'),('735','735'),('418','418'),('Glory','Glory'),('Tiba','Tiba'),
  ('Microbus','Microbus'),('540','540'),('940 || 940','940 || 940'),('Sonata','Sonata'),
  ('407','407'),('Camry','Camry'),('Foreman','Foreman'),('Suran','Suran'),('X2','X2'),('Symbol','Symbol'),('J3','J3'),
  ('Explorer','Explorer'),('V3','V3'),('300','300'),('Tiggo 7','Tiggo 7'),('New Star','New Star'),('F-Type','F-Type'),
  ('Frontera','Frontera'),('340','340'),('S 500','S 500'),
  ('Rx','Rx'),('Roomster','Roomster'),('Racer','Racer'),('2104','2104'),('L 200','L 200'),('Mini Van','Mini Van'),('147','147'),
  ('Crown','Crown'),('Ateca','Ateca'),('C-HR','C-HR'),('B15','B15'),('Avensis','Avensis'),('Tiggo 8','Tiggo 8'),('Cressida','Cressida'),
  ('Materia','Materia'),('Hiace','Hiace'),
  ('E 320','E 320'),('A5','A5'),('Beetle','Beetle'),('X7','X7'),('305','305'),('V7','V7'),('335','335'),('DX3','DX3')
  ,('Mini Truck','Mini Truck'),('T500','T500'),('Lobo','Lobo'),('APV','APV'),('Oka','Oka'),('Ideal','Ideal'),('Mark','Mark'),
  ('M70','M70'),
  ('S 350','S 350'),('Englon','Englon'),('Panda','Panda'),('Applause','Applause'),('A15','A15'),('Kalina','Kalina'),('XD','XD')
  ,('A 180','A 180'),('S 63 AMG','S 63 AMG'),('CRV','CRV'),('Urvan','Urvan'),('Celerio','Celerio'),('A25','A25'),('Tiggo 4','Tiggo 4')
  ,('Grand i10','Grand i10'),('Jumpy','Jumpy'),
  ('Mirage','Mirage'),('2110','2110'),('B-Max','B-Max'),('MCV || MCV','MCV || MCV'),('X25','X25'),('190','190'),('A6','A6')
  ,('626','626'),('180B','180B'),('S 320','S 320'),('Spark EV','Spark EV'),('Tico','Tico'),('PT Cruiser','PT Cruiser'),('605','605')
  ,('Coupe','Coupe'),('Patrol','Patrol'),
  ('308 sw','308 sw'),('Starlet','Starlet'),('Eado','Eado'),('Altea XL','Altea XL'),('Rapid','Rapid'),('Galloper','Galloper')
  ,('Grand C4 Spacetourer','Grand C4 Spacetourer'),('',''),('',''),('',''),('',''),('',''),
  ('A4','A4'),('H6','H6'),('Fox','Fox'),('460','460'),
 
 ('S30','S30'),('J2','J2'),('Mohave','Mohave'),('Country man','Country man'),('C 280','C 280'),('C 200 AMG','C 200 AMG')
 ,('Charger','Charger'),('Wingle 5','Wingle 5'),('CLA 180','CLA 180'),('Hover','Hover'),('116','116'),('Taurus','Taurus'),('Linea','Linea')
 ,('Peri','Peri'),('360 || MG 360 ','360 || MG 360 '),('250','250'),('144','144'),('208','208'),('Wagoneer','Wagoneer'),
 ('Flyer','Flyer'),('Bravo','Bravo'),('500 X','500 X'),('Windstar','Windstar'),('Datsun','Datsun'),('Galant','Galant')
 ,('YRV','YRV'),('K8','K8'),('XG','XG')
 ,('Suburban','Suburban'),('Sx4','Sx4'),('Altea','Altea'),('Feroza','Feroza'),('Dedra','Dedra'),('SLC','SLC'),
 ('C3 Picasso','C3 Picasso'),('C 300','C 300'),('XE','XE'),('X Pandino','X Pandino'),('GLC 300','GLC 300')
 ,('H 3','H 3'),('Eagle pro','Eagle pro'),('V 60','V 60'),('Cross','Cross')
 ,('Eagle','Eagle'),('STS','STS'),('Cayenne S','Cayenne S'),('Nubira','Nubira'),('19','19'),('Q2','Q2'),('Durango','Durango')
 ,('S Class','S Class'),('Fiorino','Fiorino'),('EC7','EC7'),('Z100','Z100'),('Ds4','Ds4'),('foison || Foison','foison || Foison')
 ,('750','750'),('Chairman','Chairman')
 ,('Tiggo 2','Tiggo 2'),('Chery QQ || Chery qq','Chery QQ || Chery qq'),('E Class || E Class','E Class || E Class'),
 ('XJ','XJ'),('Ram','Ram'),('328','328'),('325','325'),('Charmant','Charmant'),('Caddy','Caddy'),('Cielo','Cielo'),('126','126')
 ,('Marea','Marea'),('Albea','Albea'),('Auris','Auris'),('CLA AMG','CLA AMG')
 ,('Cayenne','Cayenne'),('Puma','Puma'),('XA','XA'),('Aleko','Aleko'),('2106','2106'),('Vito','Vito'),
 ('A380','A380'),('Florida','Florida'),('E-pace','E-pace'),('Convertible','Convertible'),('118','118')
 ,('Traverse','Traverse'),('V101','V101'),('25','25'),('Family','Family')
 ,('LEAF','LEAF'),('Pathfinder','Pathfinder'),('Gloria','Gloria'),('146','146'),('S 400','S 400'),('Partner','Partner'),('S 300','S 300')
 ,('Stellar','Stellar'),('Mk','Mk'),('XC 40','XC 40'),('A 150','A 150'),('A13','A13'),('Park Avenue','Park Avenue'),('H2','H2'),
 ('Countryman S','Countryman S')
 ,('Eos','Eos'),('Discovery','Discovery'),('XJ8','XJ8'),('121','121'),('309','309'),('21','21'),('G3','G3'),('Cx 3','Cx 3')
 ,('104','104'),('Alsvin','Alsvin'),('Jinbei','Jinbei'),('Fx','Fx'),('Lr4','Lr4'),('Marsh','Marsh'),('lr3','lr3')
 ,('Sprint','Sprint'),('CL Class','CL Class'),('106','106'),('C4 Grand Picasso','C4 Grand Picasso'),('Ranger','Ranger')
 ,('California T','California T'),('535','535'),('Duster Nova','Duster Nova'),('Discovery sport','Discovery sport'),('Laguna','Laguna'),
 ('LX 570','LX 570'),('Trooper','Trooper'),('New Yorker','New Yorker'),('Stelvio','Stelvio'),('Pilot','Pilot'),
 ('MZ 40','MZ 40'),('Transporter','Transporter'),('2112','2112'),('JAZZ','JAZZ'),('Veryca','Veryca'),('Sebring','Sebring')
 ,('E 63 AMG','E 63 AMG'),('Quintet','Quintet'),('120','120'),('Cascada','Cascada'),('Rush','Rush'),('GLC 250','GLC 250'),('Familia','Familia'),
 ('Carry','Carry'),('Lodgy','Lodgy'),('X95','X95'),('850','850'),('S 280','S 280'),('EcoSport','EcoSport'),('SEL 300','SEL 300'),('E Star','E Star'),
 ('E Star','E Star'),('Commander','Commander'),('730','730'),('Amazon','Amazon'),('S6','S6'),
 ('Quattroporte','Quattroporte'),('Camaro','Camaro'),('CLC Class','CLC Class'),('Tarraco','Tarraco'),('11','11'),('Ka','Ka')
 ,('I8','I8'),('Boxster','Boxster'),('V50','V50'),('403','403'),('Foreste','Foreste'),('Legacy','Legacy'),('GX','GX'),
 ('I3','I3'),('E 230','E 230'),('280','280'),('JS4','JS4'),('S-Type','S-Type'),('ssr','ssr'),('N5','N5'),('C 230','C 230'),('218','218')
 ,('Expedition','Expedition'),('SLK Class','SLK Class'),('550','550'),('M6','M6'),
 ('Ghibli','Ghibli'),('Maxima','Maxima'),('Pacifica','Pacifica'),('Qubo','Qubo'),
 ('CRX','CRX'),('Deville','Deville'),('Rodeo','Rodeo'),('E Golf','E Golf'),('Blazer','Blazer'),('Envoy','Envoy'),
 ('Lr2','Lr2'),('2111','2111'),('A 10 || A10','A 10 || A10'),('Musso','Musso'),('Crossover','Crossover'),('404','404')
 ,('Sparky','Sparky'),('Karoq','Karoq'),('Rav 4','Rav 4'),('Dream','Dream'),('SR7','SR7'),('Astro','Astro'),('Santa Fe','Santa Fe'),
 ('',''),('',''),('',''),('',''),('',''),('',''),('',''),('',''),('',''),('',''),('',''),('',''),('',''),

 
  ('Rekord','Rekord'),('225','225'),('Trax','Trax'),('Q35','Q35'),('Model S','Model S'),('Runner','Runner'),
  ('Montero','Montero'),('CS 15','CS 15'),('Kicks','Kicks'),('Trajet','Trajet'),('Retona','Retona'),('1007','1007'),('I20','I20'),
 ('C 450','C 450'),('Bonneville','Bonneville'),('Patriot','Patriot'),('Haima 2','Haima 2'),('Neon','Neon')
 ,('Dts','Dts'),('Acadia','Acadia'),('Model X','Model X'),('Viano','Viano'),('GLK 250','GLK 250'),('Pony','Pony'),('Priora','Priora'),('F-150','F-150'),
 ('K01s','K01s'),('M Class','M Class'),('Kamiq','Kamiq'),('Touareg','Touareg'),('F0','F0'),('Bentayga','Bentayga')
 ,('M60','M60'),('306','306'),('Ds3','Ds3'),('Vivio','Vivio'),('7 Series','7 Series'),('M20','M20'),('Marbella','Marbella') ,  


  ('232','232'),('Chiron','Chiron'),('M4','M4'),('Escalade','Escalade'),('Indigo','Indigo'),('Panamera','Panamera'),
  ('Scirocco','Scirocco'),('Edge','Edge'),('Safary','Safary'),('R Class','R Class'),('Octavia Combi','Octavia Combi')
  ,('Seltos','Seltos'),('C 350','C 350'),
 ('Clubman','Clubman'),('X 30','X 30'),('Voyager','Voyager'),('Stream','Stream'),('Victoria','Victoria')
 ,('RX','RX'),('Arteon','Arteon'),('Gol','Gol'),('Thunderbird','Thunderbird'),('Compass','Compass'),('Ex','Ex'),('H3','H3')
 ,('Clarus','Clarus') ,
  ('Ducato','Ducato'),('Bluebird','Bluebird'),('Freelander','Freelander'),('Skylark','Skylark'),('620','620')
  ,('WRX','WRX'),('Z3','Z3'),('K900','K900'),('Eado plus','Eado plus'),('Gran Coupe','Gran Coupe'),('Caravan','Caravan'),('Kangoo','Kangoo')
  ,('Fleetwood','Fleetwood'),
 ('Nova','Nova'),('Cayman S','Cayman S'),('A8','A8'),('Odyssey','Odyssey'),('Cinquecento','Cinquecento'),('760','760')
 ,('J5','J5'),('Escape','Escape'),('E 220 || E 420','E 220 || E 420'),('Sienna','Sienna'),('H100','H100'),('SRX','SRX'),('Oltcit','Oltcit'),
 ('Baleno','Baleno'),('PX Cargo','PX Cargo'),('X70S','X70S'),('X35','X35'),('607','607'),('Grand Santa Fe','Grand Santa Fe')
 ,('Adam','Adam'),('Joice','Joice'),('K01','K01'),('afira Tourer','afira Tourer'),('Sierra','Sierra'),('5 Series','5 Series'),('XJ6','XJ6'),
 ('Altima','Altima'),('A 160','A 160'),('Haima 1','Haima 1'),('Variant','Variant'),('V10','V10'),('500 L','500 L'),('V60','V60'),('Fairmont','Fairmont'),
 ('A 250','A 250')
 
 ])


 Used_since = SelectField('Select Car Used_scince',choices=[('2000','2000'),('2019','2019'),('2007','2007'),
 ('2021','2021'),('2017','2017'),('2015','2015'),('2022','2022'),('2020','2020'),('2016','2016'),('2013','2013'),
 ('1998','1998'),('2011','2011'),('1997','1997'),('1995','1995'),('1987','1987'),('2012','2012'),('2008','2008'),
 ('1996','1996'),('2005','2005'),('2010','2010'),('2014','2014'),('2018','2018'),('2009','2009'),('1985','1985'),
 ('1974','1974'),('1999','1999'),('2006','2006'),('1981','1981'),('2004','2004'),('2003','2003'),('1989','1989'),
 ('1990','1990'),('1979','1979'),('2002','2002'),('1988','1988'),('1993','1993'),('1980','1980'),('1982','1982'),
 ('1976','1976'),('1994','1994'),('1991','1991'),('1984','1984'),('1977','1977'),('1986','1986'),('1986','1986'),
 ('1978','1978'),('1992','1992'),('2001','2001'),('1975','1975'),('1983','1983'),('1971','1971'),('1973','1973'),
 ('1972','1972'),('1962','1962'),('1964','1964'),('1965','1965'),('1970','1970'),('1960','1960'),('1969','1969'),
 ('1961','1961'),('1966','1966'),('1963','1963'),('1942','1942'),('1967','1967'),('1968','1968'),('1884','1884')
 
 
 
 
 
 
 
 ])
 KM=StringField('Enter Number OF Kilometers ',validators=[DataRequired()])
 Transmission = SelectField('Select Car Transmission',choices=[('manual','manual'),('CVT','CVT'),('automatic','automatic'),('DSG','DSG')
 
 ])


 City=SelectField('Select Car City',choices=[('Abu Qir','Abu Qir'),('Tagamo3 - New Cairo','Tagamo3 - New Cairo'),('Nasr city','Nasr city'),('6 October','6 October'),
 ('El Haram','El Haram'),('Cairo','Cairo'),('Alexandria','Alexandria'),
 ('Dakahlia','Dakahlia'),('Beheira','Beheira'),('Maadi','Maadi'),('Imbaba','Imbaba'),('Hurghada','Hurghada'),('Shobra','Shobra')
 ,('Sharqia','Sharqia'),('El Salam City','El Salam City'),('Zagazig','Zagazig'),('Kafr el-Sheikh','Kafr el-Sheikh'),('Ismailia','Ismailia'),
 ('Mansoura','Mansoura'),('Kafr el-Dawwar','Kafr el-Dawwar'),('Bilbeis','Bilbeis'),('Giza','Giza'),('El Minya','El Minya')
 ,('Mohandessin','Mohandessin'),('Gharbia','Gharbia'),('Kafr El Zayat','Kafr El Zayat'),('Faiyum','Faiyum'),('Quesna','Quesna'),('Al Shorouk','Al Shorouk'),
 ('Heliopolis','Heliopolis'),('Obour City','Obour City'),('Zamalek','Zamalek'),('Helwan','Helwan'),('Beni Suef','Beni Suef'),
 ('Beni Suef','Beni Suef'),('Asyut','Asyut'),('Dokki','Dokki'),('Mit Ghamr','Mit Ghamr'),('Sohag','Sohag'),('Dyarb Negm','Dyarb Negm'),
 ('Ashmoun','Ashmoun'),('Suez','Suez'),('Khanka','Khanka'),('Ain Shams','Ain Shams'),('Tanta','Tanta'),('Damanhur','Damanhur')
 ,('El Bagour','El Bagour'),('Sheikh Zayed City','Sheikh Zayed City'),('Monufia','Monufia'),('El Mahalla','El Mahalla'),('El Marg','El Marg'),
 ('Qalyub','Qalyub'),('Kafr Shukr','Kafr Shukr'),('Banha','Banha'),('Menouf','Menouf'),('Port Said','Port Said'),('Mokattam','Mokattam')
 ,('10th of Ramadan','10th of Ramadan'),('Madinaty','Madinaty'),('Shibin el Kom','Shibin el Kom'),('Aswan','Aswan'),('Qena','Qena'),
 ('Agamy','Agamy'),('Amreya','Amreya'),('Kom Ombo','Kom Ombo'),('Warraq','Warraq'),('Red Sea','Red Sea'),('Luxor','Luxor'),('Kerdasa','Kerdasa')
 ,('Rosetta','Rosetta'),('Sheraton','Sheraton'),('Sadat City','Sadat City'),('Qalyubia','Qalyubia'),
 ('Shibin El Qanater','Shibin El Qanater'),('Sharm el-Sheikh','Sharm el-Sheikh'),('Edku','Edku'),('El Manial','El Manial')
 ,('El Qanater El Khayreya','El Qanater El Khayreya'),('Marsa Matrouh','Marsa Matrouh'),('Damietta','Damietta'),('El Senbellawein','El Senbellawein')
 ,('Abu Hummus','Abu Hummus'),('Borg el arab','Borg el arab'),('Touhk','Touhk'),
 ('El Katameya','El Katameya'),('Tala','Tala'),('El Wadi El Gedid','El Wadi El Gedid'),('Zefta','Zefta'),('Minya Al Qamh','Minya Al Qamh')
 ,('Faqous','Faqous'),('Dikirnis','Dikirnis'),('El-Arish','El-Arish'),('El Gamaleya','El Gamaleya'),('Kom Hamada','Kom Hamada'),('Abu Kabir','Abu Kabir'),
 ('Saft El Laban','Saft El Laban'),('Ras Gharib','Ras Gharib'),('El Gouna','El Gouna'),('Safaga','Safaga'),('El-Alamein','El-Alamein'),('New Administrative Capital','New Administrative Capital')
 ,('Marsa Alam','Marsa Alam')
 ])
 Color=SelectField('Select Car Color',choices=[('Light grey','Light grey'),('Silver','Silver'),
 ('Dark blue','Dark blue'),('Petroleum','Petroleum'),('Gray','Gray'),('Dark red','Dark red'),('Bronze','Bronze')
 ,('Cyan','Cyan'),('Green','Green'),('Red','Red'),('White','White'),('Champagne','Champagne'),
 ('Black','Black'),('Dark green','Dark green'),('Mocha','Mocha'),('Gold','Gold'),('Olive','Olive'),('Brown','Brown'),('Eggplant','Eggplant')
 ,('Beige','Beige'),('Purple','Purple'),('Orange','Orange'),
 ('Yellow','Yellow')
 ])
 Fuel=SelectField('Select Car Fuel',choices=[('gas','gas'),('natural gas','natural gas'),('diesel','diesel'),('Hybrid','Hybrid'),('Electric','Electric')])
 Leather_seats=SelectField('Select Car Leather_seats',choices=[('True','True'),('False','False')])
 Closing_mirrors=SelectField('Select Car Closing_mirrors',choices=[('True','True'),('False','False')])
 Intelligent_parking_system=SelectField('Select Car ntelligent_parking_system',choices=[('True','True'),('False','False')])
 Sunroof=SelectField('Select Car Sunroof',choices=[('True','True'),('False','False')])
 Fabric_brushes=SelectField('Select Car Fabric_brushes',choices=[('True','True'),('False','False')])
 Air_Conditioning=SelectField('Select Car Air_Conditioning',choices=[('True','True'),('False','False')])
 Power_Steering=SelectField('Select Car Power_Steering',choices=[('True','True'),('False','False')])
 Remote_Keyless=SelectField('Select Car Remote_Keyless',choices=[('True','True'),('False','False')])
 Electric_mirrors=SelectField('Select Car Electric_mirrors',choices=[('True','True'),('False','False')])
 Front_Power_Windows=SelectField('Select Car Front_Power_Windows',choices=[('True','True'),('False','False')])
 Back_Power_Windows=SelectField('Select Car Back_Power_Windows',choices=[('True','True'),('False','False')])   
 Tinted_Glass=SelectField('Select Car Tinted_Glass',choices=[('True','True'),('False','False')]) 
 CD_Player=SelectField('Select Car CD Player',choices=[('True','True'),('False','False')])  
 DVD_Player=SelectField('Select Car DVD_Player',choices=[('True','True'),('False','False')])  

 Bluetooth=SelectField('Select Car Bluetooth',choices=[('True','True'),('False','False')])  
 Multifunction=SelectField('Select Car Multifunction',choices=[('True','True'),('False','False')])  
 Cassette_Radio=SelectField('Select Car Cassette_Radio',choices=[('True','True'),('False','False')])  
 AUX=SelectField('Select Car AUX',choices=[('True','True'),('False','False')])  
 CD_Changer=SelectField('Select Car CD_Changer',choices=[('True','True'),('False','False')])  
 USB_Port=SelectField('Select Car USB_Port',choices=[('True','True'),('False','False')])  
 Anti_theft_System=SelectField('Select Car Anti_theft_System',choices=[('True','True'),('False','False')])  
 Side_Airbag=SelectField('Select Car Side_Airbag',choices=[('True','True'),('False','False')])  
 ABS=SelectField('Select Car ABS',choices=[('True','True'),('False','False')])  
 EPS=SelectField('Select Car EPS',choices=[('True','True'),('False','False')])  
 EBD=SelectField('Select Car EBD',choices=[('True','True'),('False','False')])  
 ESP=SelectField('Select Car ESP',choices=[('True','True'),('False','False')])  
 Sensors=SelectField('Select Car Sensors',choices=[('True','True'),('False','False')])  
 Rear_sensors=SelectField('Select Car Rear_sensors',choices=[('True','True'),('False','False')])  
 Driver_Airbag=SelectField('Select Car Driver_Airbag',choices=[('True','True'),('False','False')])  
 Passenger_Airbag=SelectField('Select Car Passenger_Airbag',choices=[('True','True'),('False','False')])  
 Front_sensors=SelectField('Select Car Front_sensors',choices=[('True','True'),('False','False')])  
 Alloy_wheels=SelectField('Select Car Alloy_wheels',choices=[('True','True'),('False','False')])  
 Rear_camera=SelectField('Select Car Rear_camera',choices=[('True','True'),('False','False')])  
 GPS=SelectField('Select Car GPS',choices=[('True','True'),('False','False')])  
 Fog_light=SelectField('Select Car Fog_light',choices=[('True','True'),('False','False')])  
 Rear_spoiler=SelectField('Select Car Rear spoiler',choices=[('True','True'),('False','False')])  
 Cruise_control=SelectField('Select Car Cruise_control',choices=[('True','True'),('False','False')])  
 Power_Seats=SelectField('Select Car Power_Seats',choices=[('True','True'),('False','False')])  
 Central_lock=SelectField('Select Car Central_lock',choices=[('True','True'),('False','False')])  
 Alarm=SelectField('Select Car Alarm',choices=[('True','True'),('False','False')])  
 submit = SubmitField('Predict Price')

@app.route('/',methods=['GET','POST'])
def index():
    form=InfoForm()
    if form.validate_on_submit():
        # Make = form.Make.data
        # Model = form.Model.data
        # Used_since = form.Used_since.data
        # KM=form.KM.data
        # Transmission = form.Transmission.data
        # City=form.City.data
        # Color=form.Color.data
        # Fuel=form.Fuel.data
        # Leather_seats=form.Leather_seats.data
        # Closing_mirrors=form.Closing_mirrors.data
        # Intelligent_parking_system=form.Intelligent_parking_system.data
        # Sunroof=form.Sunroof.data
        # Fabric_brushes=form.Fabric_brushes.data
        # Air_Conditioning=form.Air_Conditioning.data
        # Power_Steering=form.Power_Steering.data
        # Remote_Keyless=form.Remote_Keyless.data
        # Electric_mirrors=form.Electric_mirrors.data
        # Front_Power_Windows=form.Front_Power_Windows.data
        # Back_Power_Windows=form.Back_Power_Windows.data
        # Tinted_Glass=form.Tinted_Glass.data
        # CD_Player=form.CD_Player.data
        # DVD_Player=form.DVD_Player.data
        # Bluetooth=form.Bluetooth.data
        # Multifunction=form.Multifunction.data
        # Cassette_Radio=form.Cassette_Radio.data
        # AUX=form.AUX.data
        # CD_Changer=form.CD_Changer.data
        # USB_Port=form.USB_Port.data
        # Anti_theft_System=form.Anti_theft_System.data
        # Side_Airbag=form.Side_Airbag.data
        # ABS=form.ABS.data
        # EPS=form.EPS.data
        # EBD=form.EBD.data
        # ESP=form.ESP.data
        # Sensors=form.Sensors.data
        # Rear_sensors=form.Rear_sensors.data
        # Driver_Airbag=form.Driver_Airbag.data
        # Passenger_Airbag=form.Passenger_Airbag.data
        # Front_sensors=form.Front_sensors.data
        # Alloy_wheels=form.Alloy_wheels.data
        # Rear_camera=form.Rear_camera.data
        # GPS=form.GPS.data
        # Fog_light=form.Fog_light.data
        # Rear_spoiler=form.Rear_spoiler.data
        # Cruise_control=form.Cruise_control.data
        # Power_Seats=form.Power_Seats.data
        # Central_lock=form.DVD_Player.data
        # Alarm=form.Alarm.data

        data=[]
        data.append(form.KM.data)
        data.append(form.Leather_seats.data=='True')
        data.append(form.Closing_mirrors.data=='True')
        data.append(form.Intelligent_parking_system.data=='True')
        data.append(form.Sunroof.data=='True')
        data.append(form.Fabric_brushes.data=='True')
        data.append(form.Air_Conditioning.data=='True')
        data.append(form.Power_Steering.data=='True')
        data.append(form.Remote_Keyless.data=='True')
        data.append(form.Electric_mirrors.data=='True')
        data.append(form.Front_Power_Windows.data=='True')
        data.append(form.Back_Power_Windows.data=='True')
        data.append(form.Tinted_Glass.data=='True')
        data.append(form.CD_Player.data=='True')
        data.append(form.DVD_Player.data=='True')
        data.append(form.Bluetooth.data=='True')
        data.append(form.Multifunction.data=='True')
        data.append(form.Cassette_Radio.data=='True')
        data.append(form.AUX.data=='True')
        data.append(form.CD_Changer.data=='True')
        data.append(form.USB_Port.data=='True')
        data.append(form.Anti_theft_System.data=='True')
        data.append(form.Side_Airbag.data=='True')
        data.append(form.ABS.data=='True')
        data.append(form.EPS.data=='True')
        data.append(form.EBD.data=='True')
        data.append(form.ESP.data=='True')
        data.append(form.Sensors.data=='True')
        data.append(form.Rear_sensors.data=='True')
        data.append(form.Driver_Airbag.data=='True')
        data.append(form.Passenger_Airbag.data=='True')
        data.append(form.Front_sensors.data=='True')
        data.append(form.Alloy_wheels.data=='True')
        data.append(form.Rear_camera.data=='True')
        data.append(form.GPS.data=='True')
        data.append(form.Fog_light.data=='True')
        data.append(form.Rear_spoiler.data=='True')
        data.append(form.Cruise_control.data=='True')
        data.append(form.Power_Seats.data=='True')
        data.append(form.Central_lock.data=='True')

        data.append(form.Alarm.data=='True')



        data.append(form.Make.data=='Audi')
        data.append(form.Make.data=='BMW')
        data.append(form.Make.data=='Baic')
        data.append(form.Make.data=='Bentley')
        data.append(form.Make.data=='Brilliance')
        data.append(form.Make.data=='Buick')
        data.append(form.Make.data=='Byd')
        data.append(form.Make.data=='Cadillac')
        data.append(form.Make.data=='Canghe || Changhe')
        data.append(form.Make.data=='Chana')
        data.append(form.Make.data=='Changan')
        data.append(form.Make.data=='Chery')
        data.append(form.Make.data=='Chevrolet')
        data.append(form.Make.data=='Chrysler')
        data.append(form.Make.data=='Citro�n')
        data.append(form.Make.data=='DFM')
        data.append(form.Make.data=='DFSK')
        data.append(form.Make.data=='Daewoo')
        data.append(form.Make.data=='Daihatsu')
        data.append(form.Make.data=='Datsun')
        data.append(form.Make.data=='Dodge')
        data.append(form.Make.data=='Domy')
        data.append(form.Make.data=='Ds')
        data.append(form.Make.data=='Emgrand')
        data.append(form.Make.data=='Faw')
        data.append(form.Make.data=='Fiat')
        data.append(form.Make.data=='Ford')
        data.append(form.Make.data=='Foton')
        data.append(form.Make.data=='Geely')
        data.append(form.Make.data=='Gmc')
        data.append(form.Make.data=='Great Wall')
        data.append(form.Make.data=='Hafei')
        data.append(form.Make.data=='Haima')
        data.append(form.Make.data=='Haval')
        data.append(form.Make.data=='Hawtai')
        data.append(form.Make.data=='Honda')
        data.append(form.Make.data=='Hyundai')
        data.append(form.Make.data=='Infiniti')
        data.append(form.Make.data=='Isuzu')
        data.append(form.Make.data=='Jac')
        data.append(form.Make.data=='Jaguar')
        data.append(form.Make.data=='Jeep')
        data.append(form.Make.data=='Jetour')
        data.append(form.Make.data=='Jonway')
        data.append(form.Make.data=='Karry')
        data.append(form.Make.data=='Kenbo')
        data.append(form.Make.data=='Keyton')
        data.append(form.Make.data=='Kia')
        data.append(form.Make.data=='Lada')
        data.append(form.Make.data=='Lancia')
        data.append(form.Make.data=='Land Rover')
        data.append(form.Make.data=='Landwind')
        data.append(form.Make.data=='Lexus')
        data.append(form.Make.data=='Lifan')
        data.append(form.Make.data=='MG')
        data.append(form.Make.data=='Mahindra')
        data.append(form.Make.data=='Mazda')
        data.append(form.Make.data=='Mercedes')
        data.append(form.Make.data=='Mini')
        data.append(form.Make.data=='Mitsubishi')
        data.append(form.Make.data=='Nissan')
        data.append(form.Make.data=='Opel')
        data.append(form.Make.data=='Peugeot')
        data.append(form.Make.data=='Pontiac')
        data.append(form.Make.data=='Porsche')
        data.append(form.Make.data=='Proton')
        data.append(form.Make.data=='Renault')
        data.append(form.Make.data=='Saipa')
        data.append(form.Make.data=='Seat')
        data.append(form.Make.data=='Senova')
        data.append(form.Make.data=='Skoda')
        data.append(form.Make.data=='Sokon')
        data.append(form.Make.data=='Soueast')
        data.append(form.Make.data=='Speranza')
        data.append(form.Make.data=='Ssang Yong')
        data.append(form.Make.data=='Subaru')
        data.append(form.Make.data=='Suzuki')
        data.append(form.Make.data=='Tata')
        data.append(form.Make.data=='Toyota')
        data.append(form.Make.data=='Volkswagen')
        data.append(form.Make.data=='Volvo')
        data.append(form.Make.data=='Zotye')

        data.append(form.Model.data=='104')
        data.append(form.Model.data=='106')
        data.append(form.Model.data=='11')
        data.append(form.Model.data=='1100')
        data.append(form.Model.data=='116')
        data.append(form.Model.data=='118')
        data.append(form.Model.data=='12')
        data.append(form.Model.data=='120')
        data.append(form.Model.data=='1200')
        data.append(form.Model.data=='121')
        data.append(form.Model.data=='124')
        data.append(form.Model.data=='125')
        data.append(form.Model.data=='126')
        data.append(form.Model.data=='127')
        data.append(form.Model.data=='128')
        data.append(form.Model.data=='1300')
        data.append(form.Model.data=='131')
        data.append(form.Model.data=='132')
        data.append(form.Model.data=='133')
        data.append(form.Model.data=='144')
        data.append(form.Model.data=='146')
        data.append(form.Model.data=='147')
        data.append(form.Model.data=='1500')
        data.append(form.Model.data=='156')
        data.append(form.Model.data=='18')
        data.append(form.Model.data=='180')
        data.append(form.Model.data=='180B')
        data.append(form.Model.data=='19')
        data.append(form.Model.data=='190')
        data.append(form.Model.data=='2 || Mazda 2')
        data.append(form.Model.data=='200')
        data.append(form.Model.data=='2008')
        data.append(form.Model.data=='2017')
        data.append(form.Model.data=='205')
        data.append(form.Model.data=='206')
        data.append(form.Model.data=='207')
        data.append(form.Model.data=='208')
        data.append(form.Model.data=='21')
        data.append(form.Model.data=='2104')
        data.append(form.Model.data=='2105')
        data.append(form.Model.data=='2106')
        data.append(form.Model.data=='2107')
        data.append(form.Model.data=='2110')
        data.append(form.Model.data=='2111')
        data.append(form.Model.data=='2112')
        data.append(form.Model.data=='218')
        data.append(form.Model.data=='218 i')
        data.append(form.Model.data=='225')
        data.append(form.Model.data=='230')
        data.append(form.Model.data=='232')
        data.append(form.Model.data=='240')
        data.append(form.Model.data=='244')
        data.append(form.Model.data=='25')
        data.append(form.Model.data=='250')
        data.append(form.Model.data=='280')
        data.append(form.Model.data=='3')
        data.append(form.Model.data=='3 || Mazda 3')
        data.append(form.Model.data=='300')
        data.append(form.Model.data=='3008')
        data.append(form.Model.data=='301')
        data.append(form.Model.data=='304')
        data.append(form.Model.data=='305')
        data.append(form.Model.data=='306')
        data.append(form.Model.data=='307')
        data.append(form.Model.data=='308')
        data.append(form.Model.data=='308 sw')
        data.append(form.Model.data=='309')
        data.append(form.Model.data=='316')
        data.append(form.Model.data=='318')
        data.append(form.Model.data=='320')
        data.append(form.Model.data=='323')
        data.append(form.Model.data=='325')
        data.append(form.Model.data=='328')
        data.append(form.Model.data=='330')
        data.append(form.Model.data=='330S')
        data.append(form.Model.data=='340')
        data.append(form.Model.data=='350')
        data.append(form.Model.data=='360 || MG 360')
        data.append(form.Model.data=='403')
        data.append(form.Model.data=='404')
        data.append(form.Model.data=='405')
        data.append(form.Model.data=='406')
        data.append(form.Model.data=='407')
        data.append(form.Model.data=='408')
        data.append(form.Model.data=='418')
        data.append(form.Model.data=='460')
        data.append(form.Model.data=='5')
        data.append(form.Model.data=='5 Series')
        data.append(form.Model.data=='500')
        data.append(form.Model.data=='500 L')
        data.append(form.Model.data=='500 X')
        data.append(form.Model.data=='5008')
        data.append(form.Model.data=='504')
        data.append(form.Model.data=='505')
        data.append(form.Model.data=='508')
        data.append(form.Model.data=='518')
        data.append(form.Model.data=='520')
        data.append(form.Model.data=='523')
        data.append(form.Model.data=='525')
        data.append(form.Model.data=='528')
        data.append(form.Model.data=='530')
        data.append(form.Model.data=='535')
        data.append(form.Model.data=='540')
        data.append(form.Model.data=='550')
        data.append(form.Model.data=='6')
        data.append(form.Model.data=='605')
        data.append(form.Model.data=='607')
        data.append(form.Model.data=='620')
        data.append(form.Model.data=='626')
        data.append(form.Model.data=='650')
        data.append(form.Model.data=='7 Series')
        data.append(form.Model.data=='730')
        data.append(form.Model.data=='735')
        data.append(form.Model.data=='740')
        data.append(form.Model.data=='750')
        data.append(form.Model.data=='760')
        data.append(form.Model.data=='80')
        data.append(form.Model.data=='850')
        data.append(form.Model.data=='9')
        data.append(form.Model.data=='929')
        data.append(form.Model.data=='940 || 940')
        data.append(form.Model.data=='A 10 || A10')
        data.append(form.Model.data=='A 150')
        data.append(form.Model.data=='A 160')
        data.append(form.Model.data=='A 180')
        data.append(form.Model.data=='A 200')
        data.append(form.Model.data=='A1')
        data.append(form.Model.data=='A11')
        data.append(form.Model.data=='A113')
        data.append(form.Model.data=='A13')
        data.append(form.Model.data=='A15')
        data.append(form.Model.data=='A213')
        data.append(form.Model.data=='A25')
        data.append(form.Model.data=='A3')
        data.append(form.Model.data=='A380')
        data.append(form.Model.data=='A4')
        data.append(form.Model.data=='A5')
        data.append(form.Model.data=='A516')
        data.append(form.Model.data=='A6')
        data.append(form.Model.data=='A620 || A620')
        data.append(form.Model.data=='APV')
        data.append(form.Model.data=='Acadia')
        data.append(form.Model.data=='Accent')
        data.append(form.Model.data=='Accent HCI')
        data.append(form.Model.data=='Accent RB')
        data.append(form.Model.data=='Accord')
        data.append(form.Model.data=='Adam')
        data.append(form.Model.data=='Albea')
        data.append(form.Model.data=='Aleko')
        data.append(form.Model.data=='Alsvin')
        data.append(form.Model.data=='Altea')
        data.append(form.Model.data=='Altea XL')
        data.append(form.Model.data=='Altima')
        data.append(form.Model.data=='Alto')
        data.append(form.Model.data=='Amazon')
        data.append(form.Model.data=='Applause')
        data.append(form.Model.data=='Argenta')
        data.append(form.Model.data=='Arrizo 3')
        data.append(form.Model.data=='Arrizo 5')
        data.append(form.Model.data=='Astra')
        data.append(form.Model.data=='Astro')
        data.append(form.Model.data=='Ateca')
        data.append(form.Model.data=='Atos')
        data.append(form.Model.data=='Attrage')
        data.append(form.Model.data=='Auris')
        data.append(form.Model.data=='Avante')
        data.append(form.Model.data=='Avanza')
        data.append(form.Model.data=='Avensis')
        data.append(form.Model.data=='Aveo')
        data.append(form.Model.data=='Ax')
        data.append(form.Model.data=='Azure')
        data.append(form.Model.data=='B 150')
        data.append(form.Model.data=='B 160')
        data.append(form.Model.data=='B 180')
        data.append(form.Model.data=='B 200')
        data.append(form.Model.data=='B-Max')
        data.append(form.Model.data=='B15')
        data.append(form.Model.data=='Baleno')
        data.append(form.Model.data=='Beetle')
        data.append(form.Model.data=='Belta')
        data.append(form.Model.data=='Benni')
        data.append(form.Model.data=='Berlingo')
        data.append(form.Model.data=='Besturn')
        data.append(form.Model.data=='Blazer')
        data.append(form.Model.data=='Bluebird')
        data.append(form.Model.data=='Bonneville')
        data.append(form.Model.data=='Bora')
        data.append(form.Model.data=='Brava')
        data.append(form.Model.data=='Bravo')
        data.append(form.Model.data=='C 180')
        data.append(form.Model.data=='C 200')
        data.append(form.Model.data=='C 200 AMG')
        data.append(form.Model.data=='C 230')
        data.append(form.Model.data=='C 240')
        data.append(form.Model.data=='C 250')
        data.append(form.Model.data=='C 280')
        data.append(form.Model.data=='C 300')
        data.append(form.Model.data=='C Elysee')
        data.append(form.Model.data=='C-HR')
        data.append(form.Model.data=='C3')
        data.append(form.Model.data=='C3 Aircross')
        data.append(form.Model.data=='C3 Picasso')
        data.append(form.Model.data=='C30')
        data.append(form.Model.data=='C4')
        data.append(form.Model.data=='C4 Grand Picasso')
        data.append(form.Model.data=='C4 Picasso')
        data.append(form.Model.data=='C5')
        data.append(form.Model.data=='C5 Aircross')
        data.append(form.Model.data=='CC')
        data.append(form.Model.data=='CRV')
        data.append(form.Model.data=='CRX')
        data.append(form.Model.data=='CS 15')
        data.append(form.Model.data=='CS 35')
        data.append(form.Model.data=='Caddy')
        data.append(form.Model.data=='Camaro')
        data.append(form.Model.data=='Camry')
        data.append(form.Model.data=='Caprice')
        data.append(form.Model.data=='Captiva')
        data.append(form.Model.data=='Captur')
        data.append(form.Model.data=='Caravan')
        data.append(form.Model.data=='Carens')
        data.append(form.Model.data=='Carina')
        data.append(form.Model.data=='Carnival')
        data.append(form.Model.data=='Carry')
        data.append(form.Model.data=='Cascada')
        data.append(form.Model.data=='Cayenne')
        data.append(form.Model.data=='Cayenne S')
        data.append(form.Model.data=='Ceed')
        data.append(form.Model.data=='Celerio')
        data.append(form.Model.data=='Cerato')
        data.append(form.Model.data=='Chairman')
        data.append(form.Model.data=='Charade')
        data.append(form.Model.data=='Charmant')
        data.append(form.Model.data=='Cherokee')
        data.append(form.Model.data=='_Chery QQ || Chery qq')
        data.append(form.Model.data=='Ciaz')
        data.append(form.Model.data=='Cielo')
        data.append(form.Model.data=='Cinquecento')
        data.append(form.Model.data=='City')
        data.append(form.Model.data=='Civic')
        data.append(form.Model.data=='Ck')
        data.append(form.Model.data=='Ck2')
        data.append(form.Model.data=='Clarus')
        data.append(form.Model.data=='Clio')
        data.append(form.Model.data=='Clubman')
        data.append(form.Model.data=='Colt')
        data.append(form.Model.data=='Commander')
        data.append(form.Model.data=='Convertible')
        data.append(form.Model.data=='Cooper')
        data.append(form.Model.data=='Cordoba')
        data.append(form.Model.data=='Corolla')
        data.append(form.Model.data=='Corolla Cross')
        data.append(form.Model.data=='Corona')
        data.append(form.Model.data=='Corsa')
        data.append(form.Model.data=='Country man')
        data.append(form.Model.data=='Countryman S')
        data.append(form.Model.data=='Coupe')
        data.append(form.Model.data=='Cressida')
        data.append(form.Model.data=='Creta')
        data.append(form.Model.data=='Cross')
        data.append(form.Model.data=='Crossland')
        data.append(form.Model.data=='Crossover')
        data.append(form.Model.data=='Crown')
        data.append(form.Model.data=='Cruze')
        data.append(form.Model.data=='Cx 3')
        data.append(form.Model.data=='D max')
        data.append(form.Model.data=='DS5')
        data.append(form.Model.data=='DX3')
        data.append(form.Model.data=='Dakota')
        data.append(form.Model.data=='Dart')
        data.append(form.Model.data=='Datsun')
        data.append(form.Model.data=='Dedra')
        data.append(form.Model.data=='Delta')
        data.append(form.Model.data=='Deville')
        data.append(form.Model.data=='Discovery')
        data.append(form.Model.data=='Doblo')
        data.append(form.Model.data=='Dogan')
        data.append(form.Model.data=='Dream')
        data.append(form.Model.data=='Ds3')
        data.append(form.Model.data=='Ds4')
        data.append(form.Model.data=='Dts')
        data.append(form.Model.data=='Ducato')
        data.append(form.Model.data=='Durango')
        data.append(form.Model.data=='Duster')
        data.append(form.Model.data=='Duster Nova')
        data.append(form.Model.data=='E 180')
        data.append(form.Model.data=='E 200')
        data.append(form.Model.data=='E 200 AMG')
        data.append(form.Model.data=='E 220')
        data.append(form.Model.data=='E 220 || E 420')
        data.append(form.Model.data=='E 230')
        data.append(form.Model.data=='E 240')
        data.append(form.Model.data=='E 250')
        data.append(form.Model.data=='E 280')
        data.append(form.Model.data=='E 300')
        data.append(form.Model.data=='E 320')
        data.append(form.Model.data=='E 350')
        data.append(form.Model.data=='E Golf')
        data.append(form.Model.data=='E Star')
        data.append(form.Model.data=='EAGLE 580')
        data.append(form.Model.data=='EC 7')
        data.append(form.Model.data=='EC7')
        data.append(form.Model.data=='Eado')
        data.append(form.Model.data=='Eado plus')
        data.append(form.Model.data=='Eagle')
        data.append(form.Model.data=='Eagle pro')
        data.append(form.Model.data=='Echo')
        data.append(form.Model.data=='Eclipse')
        data.append(form.Model.data=='Eclipse Cross')
        data.append(form.Model.data=='EcoSport')
        data.append(form.Model.data=='Edge')
        data.append(form.Model.data=='Elantra')
        data.append(form.Model.data=='Elantra AD')
        data.append(form.Model.data=='Elantra CN7')
        data.append(form.Model.data=='Elantra HD')
        data.append(form.Model.data=='Elantra MD')
        data.append(form.Model.data=='Emgrand 7')
        data.append(form.Model.data=='Emgrand X7')
        data.append(form.Model.data=='Englon')
        data.append(form.Model.data=='Envoy')
        data.append(form.Model.data=='Envy')
        data.append(form.Model.data=='Eos')
        data.append(form.Model.data=='Equinox')
        data.append(form.Model.data=='Ertiga')
        data.append(form.Model.data=='Escalade')
        data.append(form.Model.data=='Escape')
        data.append(form.Model.data=='Escort')
        data.append(form.Model.data=='Espero')
        data.append(form.Model.data=='Ex')
        data.append(form.Model.data=='Excel')
        data.append(form.Model.data=='Expedition')
        data.append(form.Model.data=='Explorer')
        data.append(form.Model.data=='F-150')
        data.append(form.Model.data=='F0')
        data.append(form.Model.data=='F3')
        data.append(form.Model.data=='FRV')
        data.append(form.Model.data=='FRV Cross')
        data.append(form.Model.data=='FSV')
        data.append(form.Model.data=='Fabia')
        data.append(form.Model.data=='Fairmont')
        data.append(form.Model.data=='Familia')
        data.append(form.Model.data=='Family')
        data.append(form.Model.data=='Fantasia')
        data.append(form.Model.data=='Favorit')
        data.append(form.Model.data=='Felicia')
        data.append(form.Model.data=='Felicia combi')
        data.append(form.Model.data=='Feroza')
        data.append(form.Model.data=='Fiesta')
        data.append(form.Model.data=='Fiorino')
        data.append(form.Model.data=='Fleetwood')
        data.append(form.Model.data=='Florid')
        data.append(form.Model.data=='Florida')
        data.append(form.Model.data=='Fluence')
        data.append(form.Model.data=='Flyer')
        data.append(form.Model.data=='Focus')
        data.append(form.Model.data=='Foreman')
        data.append(form.Model.data=='Foreste')
        data.append(form.Model.data=='Forte')
        data.append(form.Model.data=='Fortuner')
        data.append(form.Model.data=='Fox')
        data.append(form.Model.data=='Freelander')
        data.append(form.Model.data=='Frontera')
        data.append(form.Model.data=='Fruits')
        data.append(form.Model.data=='Fusion')
        data.append(form.Model.data=='G3')
        data.append(form.Model.data=='GLK')
        data.append(form.Model.data=='GLK 350')
        data.append(form.Model.data=='Galant')
        data.append(form.Model.data=='Galena')
        data.append(form.Model.data=='Galloper')
        data.append(form.Model.data=='Gen 2')
        data.append(form.Model.data=='Getz')
        data.append(form.Model.data=='Giulietta')
        data.append(form.Model.data=='Gloria')
        data.append(form.Model.data=='Glory')
        data.append(form.Model.data=='Glory 330')
        data.append(form.Model.data=='Gol')
        data.append(form.Model.data=='Golf')
        data.append(form.Model.data=='Gran Coupe')
        data.append(form.Model.data=='Gran max')
        data.append(form.Model.data=='Grand C-Max')
        data.append(form.Model.data=='Grand C4 Spacetourer')
        data.append(form.Model.data=='Grand Cerato')
        data.append(form.Model.data=='Grand Cherokee')
        data.append(form.Model.data=='Grand Santa Fe')
        data.append(form.Model.data=='Grand i10')
        data.append(form.Model.data=='Grand terios')
        data.append(form.Model.data=='Grandland')
        data.append(form.Model.data=='Granta')
        data.append(form.Model.data=='H1')
        data.append(form.Model.data=='H100')
        data.append(form.Model.data=='H3')
        data.append(form.Model.data=='H530')
        data.append(form.Model.data=='H6')
        data.append(form.Model.data=='HRV')
        data.append(form.Model.data=='HS')
        data.append(form.Model.data=='Haima 1')
        data.append(form.Model.data=='Haima 2')
        data.append(form.Model.data=='Hiace')
        data.append(form.Model.data=='Hilux')
        data.append(form.Model.data=='Hover')
        data.append(form.Model.data=='I10')
        data.append(form.Model.data=='I20')
        data.append(form.Model.data=='I3')
        data.append(form.Model.data=='I30')
        data.append(form.Model.data=='IX 35')
        data.append(form.Model.data=='Ibiza')
        data.append(form.Model.data=='Ideal')
        data.append(form.Model.data=='Imperial')
        data.append(form.Model.data=='Impreza')
        data.append(form.Model.data=='Indigo')
        data.append(form.Model.data=='Insignia')
        data.append(form.Model.data=='Ix20')
        data.append(form.Model.data=='J2')
        data.append(form.Model.data=='J3')
        data.append(form.Model.data=='J5')
        data.append(form.Model.data=='J7')
        data.append(form.Model.data=='JAZZ')
        data.append(form.Model.data=='JS3')
        data.append(form.Model.data=='JS4')
        data.append(form.Model.data=='Jetta')
        data.append(form.Model.data=='Jimny')
        data.append(form.Model.data=='Jinbei')
        data.append(form.Model.data=='John Cooper')
        data.append(form.Model.data=='Joice')
        data.append(form.Model.data=='Jolion')
        data.append(form.Model.data=='Juke')

        data.append(form.Model.data=='Juliet')
        data.append(form.Model.data=='Jumpy')
        data.append(form.Model.data=='K01')
        data.append(form.Model.data=='K01s')
        data.append(form.Model.data=='K8')
        data.append(form.Model.data=='K900')
        data.append(form.Model.data=='Ka')
        data.append(form.Model.data=='Kadjar')
        data.append(form.Model.data=='Kalina')
        data.append(form.Model.data=='Kamiq')
        data.append(form.Model.data=='Kancil')
        data.append(form.Model.data=='Kangoo')
        data.append(form.Model.data=='Kicks')
        data.append(form.Model.data=='Komodo')
        data.append(form.Model.data=='Koup')
        data.append(form.Model.data=='Kuga')
        data.append(form.Model.data=='L 200')
        data.append(form.Model.data=='L3')
        data.append(form.Model.data=='LEAF')
        data.append(form.Model.data=='Lacetti')
        data.append(form.Model.data=='Laguna')
        data.append(form.Model.data=='Lancer')
        data.append(form.Model.data=='Land Cruiser')
        data.append(form.Model.data=='Lanos')
        data.append(form.Model.data=='Lanos 2')
        data.append(form.Model.data=='Legacy')
        data.append(form.Model.data=='Leganza')
        data.append(form.Model.data=='Leon')
        data.append(form.Model.data=='Liberty')
        data.append(form.Model.data=='Linea')
        data.append(form.Model.data=='Livina')
        data.append(form.Model.data=='Lobo')
        data.append(form.Model.data=='Lodgy')
        data.append(form.Model.data=='Logan')
        data.append(form.Model.data=='Lr2')
        data.append(form.Model.data=='Lumina')
        data.append(form.Model.data=='M Class')
        data.append(form.Model.data=='M11')
        data.append(form.Model.data=='M12')
        data.append(form.Model.data=='M20')
        data.append(form.Model.data=='M3')
        data.append(form.Model.data=='M50 || M 50')
        data.append(form.Model.data=='M60')
        data.append(form.Model.data=='M70')
        data.append(form.Model.data=='MCV || MCV')
        data.append(form.Model.data=='ML')
        data.append(form.Model.data=='MZ 40')
        data.append(form.Model.data=='Malibu')
        data.append(form.Model.data=='Maple')
        data.append(form.Model.data=='Marbella')
        data.append(form.Model.data=='Marea')
        data.append(form.Model.data=='Mark')
        data.append(form.Model.data=='Marsh')
        data.append(form.Model.data=='Maruti')
        data.append(form.Model.data=='Materia')
        data.append(form.Model.data=='Matiz')
        data.append(form.Model.data=='Matrix')
        data.append(form.Model.data=='Maxima')
        data.append(form.Model.data=='Megane')
        data.append(form.Model.data=='Meriva')
        data.append(form.Model.data=='Microbus')
        data.append(form.Model.data=='Mini Cooper S')
        data.append(form.Model.data=='Mini Truck')
        data.append(form.Model.data=='Mini Van')
        data.append(form.Model.data=='Minivan')
        data.append(form.Model.data=='Mirage')
        data.append(form.Model.data=='Mito')
        data.append(form.Model.data=='Mk')
        data.append(form.Model.data=='Mohave')
        data.append(form.Model.data=='Mokka')
        data.append(form.Model.data=='Mondeo')
        data.append(form.Model.data=='Montero')
        data.append(form.Model.data=='Murano')
        data.append(form.Model.data=='Musso')
        data.append(form.Model.data=='N-Series')
        data.append(form.Model.data=='N200')
        data.append(form.Model.data=='N300')
        data.append(form.Model.data=='N5')
        data.append(form.Model.data=='Neon')
        data.append(form.Model.data=='New Star')
        data.append(form.Model.data=='New Yorker')
        data.append(form.Model.data=='Niva')
        data.append(form.Model.data=='Nova')
        data.append(form.Model.data=='Nubira')
        data.append(form.Model.data=='Nubira 1')
        data.append(form.Model.data=='Nubira 2')
        data.append(form.Model.data=='Octavia')
        data.append(form.Model.data=='Octavia A4')
        data.append(form.Model.data=='Octavia A5')
        data.append(form.Model.data=='Octavia A7')
        data.append(form.Model.data=='Octavia Combi')
        data.append(form.Model.data=='Odyssey')
        data.append(form.Model.data=='Oka')
        data.append(form.Model.data=='Oltcit')
        data.append(form.Model.data=='Optima')
        data.append(form.Model.data=='Optra')
        data.append(form.Model.data=='Outlander')
        data.append(form.Model.data=='PT Cruiser')
        data.append(form.Model.data=='PX Cargo')
        data.append(form.Model.data=='Pacifica')
        data.append(form.Model.data=='Pajero')
        data.append(form.Model.data=='Palio')
        data.append(form.Model.data=='Panamera')
        data.append(form.Model.data=='Panda')
        data.append(form.Model.data=='Pandino')
        data.append(form.Model.data=='Parati')
        data.append(form.Model.data=='Park Avenue')
        data.append(form.Model.data=='Partner')
        data.append(form.Model.data=='Passat')
        data.append(form.Model.data=='Pathfinder')
        data.append(form.Model.data=='Patriot')
        data.append(form.Model.data=='Patrol')
        data.append(form.Model.data=='Pegas')
        data.append(form.Model.data=='Peri')
        data.append(form.Model.data=='Persona')
        data.append(form.Model.data=='Petra')
        data.append(form.Model.data=='Picanto')
        data.append(form.Model.data=='Pick up')
        data.append(form.Model.data=='Pickup')
        data.append(form.Model.data=='Pilot')
        data.append(form.Model.data=='Pointer')
        data.append(form.Model.data=='Polo')
        data.append(form.Model.data=='Polonez')
        data.append(form.Model.data=='Pony')
        data.append(form.Model.data=='Prado')
        data.append(form.Model.data=='Preve')
        data.append(form.Model.data=='Pride')
        data.append(form.Model.data=='Priora')
        data.append(form.Model.data=='Puma')
        data.append(form.Model.data=='Punto')
        data.append(form.Model.data=='Punto evo')
        data.append(form.Model.data=='Q22')
        data.append(form.Model.data=='Q3')
        data.append(form.Model.data=='Q35')
        data.append(form.Model.data=='Q5')
        data.append(form.Model.data=='Q7')
        data.append(form.Model.data=='Qashqai')
        data.append(form.Model.data=='Qubo')
        data.append(form.Model.data=='Quintet')
        data.append(form.Model.data=='RCZ')
        data.append(form.Model.data=='RX')
        data.append(form.Model.data=='Racer')
        data.append(form.Model.data=='Rainbow')
        data.append(form.Model.data=='Ram')
        data.append(form.Model.data=='Range Rover')
        data.append(form.Model.data=='Range Rover Evoque || Evoque')
        data.append(form.Model.data=='Ranger')
        data.append(form.Model.data=='Rapid')
        data.append(form.Model.data=='Rapid Spaceback')
        data.append(form.Model.data=='Rav 4')
        data.append(form.Model.data=='Regata')
        data.append(form.Model.data=='Rekord')
        data.append(form.Model.data=='Renegade')
        data.append(form.Model.data=='Retona')
        data.append(form.Model.data=='Rio')
        data.append(form.Model.data=='Ritmo')
        data.append(form.Model.data=='Rodeo')
        data.append(form.Model.data=='Roomster')
        data.append(form.Model.data=='Runner')
        data.append(form.Model.data=='Rush')
        data.append(form.Model.data=='Rx')
        data.append(form.Model.data=='Rx5')
        data.append(form.Model.data=='S 280')
        data.append(form.Model.data=='S 300')
        data.append(form.Model.data=='S 320')
        data.append(form.Model.data=='S 350')
        data.append(form.Model.data=='S 500')
        data.append(form.Model.data=='S Class')
        data.append(form.Model.data=='S Presso')
        data.append(form.Model.data=='S-Type')
        data.append(form.Model.data=='S2')
        data.append(form.Model.data=='S3')
        data.append(form.Model.data=='S30')
        data.append(form.Model.data=='S4')
        data.append(form.Model.data=='S40')
        data.append(form.Model.data=='S5')
        data.append(form.Model.data=='S6')
        data.append(form.Model.data=='S60')
        data.append(form.Model.data=='S7')
        data.append(form.Model.data=='S80')
        data.append(form.Model.data=='SEL 280')
        data.append(form.Model.data=='SEL 300')
        data.append(form.Model.data=='SEL 500')
        data.append(form.Model.data=='SIRION')
        data.append(form.Model.data=='SLK Class')
        data.append(form.Model.data=='SR7')
        data.append(form.Model.data=='SRX')
        data.append(form.Model.data=='STS')
        data.append(form.Model.data=='Safary')
        data.append(form.Model.data=='Saga')
        data.append(form.Model.data=='Saipa')
        data.append(form.Model.data=='Samara')
        data.append(form.Model.data=='Sandero')
        data.append(form.Model.data=='Sandero Step Way')
        data.append(form.Model.data=='Santa Fe')
        data.append(form.Model.data=='Santamo')
        data.append(form.Model.data=='Scala')
        data.append(form.Model.data=='Scenic')
        data.append(form.Model.data=='Scirocco')
        data.append(form.Model.data=='Scorpio')
        data.append(form.Model.data=='Sebring')
        data.append(form.Model.data=='Sentra')
        data.append(form.Model.data=='Sephia')
        data.append(form.Model.data=='Shahin')
        data.append(form.Model.data=='Shuma')
        data.append(form.Model.data=='Siena')
        data.append(form.Model.data=='Skylark')
        data.append(form.Model.data=='Solaris')
        data.append(form.Model.data=='Sonata')
        data.append(form.Model.data=='Sonic')
        data.append(form.Model.data=='Sorento')
        data.append(form.Model.data=='Soul')
        data.append(form.Model.data=='Spark')
        data.append(form.Model.data=='Spark EV')
        data.append(form.Model.data=='Spark Lite')
        data.append(form.Model.data=='Sparky')
        data.append(form.Model.data=='Spectra')
        data.append(form.Model.data=='Splendor')
        data.append(form.Model.data=='Sportage')
        data.append(form.Model.data=='Sprint')
        data.append(form.Model.data=='Starlet')
        data.append(form.Model.data=='Stellar')
        data.append(form.Model.data=='Stream')
        data.append(form.Model.data=='Sunny')
        data.append(form.Model.data=='Superb')
        data.append(form.Model.data=='Suran')
        data.append(form.Model.data=='Swift')
        data.append(form.Model.data=='Swift Dzire || Dzire')
        data.append(form.Model.data=='Sx4')
        data.append(form.Model.data=='Symbol')
        data.append(form.Model.data=='T-Series')
        data.append(form.Model.data=='T500')
        data.append(form.Model.data=='T600')
        data.append(form.Model.data=='Taurus')
        data.append(form.Model.data=='Tempra')
        data.append(form.Model.data=='Tercel')
        data.append(form.Model.data=='Terios')
        data.append(form.Model.data=='Thunderbird')
        data.append(form.Model.data=='Tiba')
        data.append(form.Model.data=='Tico')
        data.append(form.Model.data=='Tiggo')
        data.append(form.Model.data=='Tiggo 2')
        data.append(form.Model.data=='Tiggo 3')
        data.append(form.Model.data=='Tiggo 4')
        data.append(form.Model.data=='Tiggo 7')
        data.append(form.Model.data=='Tiggo 7 pro')
        data.append(form.Model.data=='Tiggo 8')
        data.append(form.Model.data=='Tigra')
        data.append(form.Model.data=='Tiguan')
        data.append(form.Model.data=='Tiida')
        data.append(form.Model.data=='Tipo')
        data.append(form.Model.data=='Tivoli')
        data.append(form.Model.data=='Tivoli XLV')
        data.append(form.Model.data=='Toledo')
        data.append(form.Model.data=='Touareg')
        data.append(form.Model.data=='Town & Country')
        data.append(form.Model.data=='Trajet')
        data.append(form.Model.data=='Transporter')
        data.append(form.Model.data=='Traverse')
        data.append(form.Model.data=='Trax')
        data.append(form.Model.data=='Trooper')
        data.append(form.Model.data=='Tucson')
        data.append(form.Model.data=='Tucson GDI')
        data.append(form.Model.data=='Turan')
        data.append(form.Model.data=='Uno')
        data.append(form.Model.data=='Urvan')
        data.append(form.Model.data=='V 60')
        data.append(form.Model.data=='V10')
        data.append(form.Model.data=='V101')

        data.append(form.Model.data=='V3')
        data.append(form.Model.data=='V5')
        data.append(form.Model.data=='V50')
        data.append(form.Model.data=='V6')
        data.append(form.Model.data=='V7')
        data.append(form.Model.data=='Van')
        data.append(form.Model.data=='Variant')
        data.append(form.Model.data=='Vectra')
        data.append(form.Model.data=='Veloster')
        data.append(form.Model.data=='Venture')
        data.append(form.Model.data=='Verna')
        data.append(form.Model.data=='Veryca')
        data.append(form.Model.data=='Viano')
        data.append(form.Model.data=='Victoria')
        data.append(form.Model.data=='Vita')
        data.append(form.Model.data=='Vitara')
        data.append(form.Model.data=='Vito')
        data.append(form.Model.data=='Viva')
        data.append(form.Model.data=='Vivio')
        data.append(form.Model.data=='Voyager')
        data.append(form.Model.data=='WRX')
        data.append(form.Model.data=='Wagoneer')
        data.append(form.Model.data=='_Waja')
        data.append(form.Model.data=='Windstar')
        data.append(form.Model.data=='Wingle 5')
        data.append(form.Model.data=='Wira')
        data.append(form.Model.data=='Wrangler')
        data.append(form.Model.data=='Wrangler Unlimited')
        data.append(form.Model.data=='X 30')
        data.append(form.Model.data=='X Pandino')
        data.append(form.Model.data=='X-Type')
        data.append(form.Model.data=='X1')
        data.append(form.Model.data=='X25')
        data.append(form.Model.data=='X3')
        data.append(form.Model.data=='X35')
        data.append(form.Model.data=='X40')
        data.append(form.Model.data=='X5')
        data.append(form.Model.data=='X7')
        data.append(form.Model.data=='X70')
        data.append(form.Model.data=='X70S')
        data.append(form.Model.data=='XA')
        data.append(form.Model.data=='XC90')
        data.append(form.Model.data=='XD')
        data.append(form.Model.data=='XG')
        data.append(form.Model.data=='XJ')
        data.append(form.Model.data=='XJ6')
        data.append(form.Model.data=='XJ8')
        data.append(form.Model.data=='XTrail || XTrail')
        data.append(form.Model.data=='XV')
        data.append(form.Model.data=='Xceed')
        data.append(form.Model.data=='Xpander')
        data.append(form.Model.data=='Xplosion')
        data.append(form.Model.data=='Xsara')
        data.append(form.Model.data=='YRV')
        data.append(form.Model.data=='Yaris')
        data.append(form.Model.data=='Yeti')
        data.append(form.Model.data=='Z100')
        data.append(form.Model.data=='Z3')
        data.append(form.Model.data=='Z300')
        data.append(form.Model.data=='ZS')
        data.append(form.Model.data=='ZX')
        data.append(form.Model.data=='Zafira Tourer')
        data.append(form.Model.data=='Zaz')
        data.append(form.Model.data=='foison || Foison')
        data.append(form.Model.data=='ideal || Ideal')
        data.append(form.Model.data=='ssr')


        data.append(form.Used_since.data=='1942.0')
        data.append(form.Used_since.data=='1960.0')
        data.append(form.Used_since.data=='1961.0')
        data.append(form.Used_since.data=='1962.0')
        data.append(form.Used_since.data=='1963.0')
        data.append(form.Used_since.data=='1964.0')
        data.append(form.Used_since.data=='1965.0')
        data.append(form.Used_since.data=='1966.0')
        data.append(form.Used_since.data=='1967.0')
        data.append(form.Used_since.data=='1968.0')
        data.append(form.Used_since.data=='1969.0')
        data.append(form.Used_since.data=='1970.0')
        data.append(form.Used_since.data=='1971.0')
        data.append(form.Used_since.data=='1972.0')
        data.append(form.Used_since.data=='1973.0')
        data.append(form.Used_since.data=='1974.0')
        data.append(form.Used_since.data=='1975.0')
        data.append(form.Used_since.data=='1976.0')
        data.append(form.Used_since.data=='1977.0')
        data.append(form.Used_since.data=='1978.0')
        data.append(form.Used_since.data=='1979.0')
        data.append(form.Used_since.data=='1980.0')
        data.append(form.Used_since.data=='1981.0')
        data.append(form.Used_since.data=='1982.0')
        data.append(form.Used_since.data=='1983.0')
        data.append(form.Used_since.data=='1984.0')
        data.append(form.Used_since.data=='1985.0')
        data.append(form.Used_since.data=='1986.0')
        data.append(form.Used_since.data=='1987.0')
        data.append(form.Used_since.data=='1988.0')
        data.append(form.Used_since.data=='1989.0')
        data.append(form.Used_since.data=='1990.0')
        data.append(form.Used_since.data=='1991.0')
        data.append(form.Used_since.data=='1992.0')
        data.append(form.Used_since.data=='1993.0')
        data.append(form.Used_since.data=='1994.0')
        data.append(form.Used_since.data=='1995.0')
        data.append(form.Used_since.data=='1996.0')
        data.append(form.Used_since.data=='1997.0')
        data.append(form.Used_since.data=='1998.0')
        data.append(form.Used_since.data=='1999.0')
        data.append(form.Used_since.data=='2000.0')
        data.append(form.Used_since.data=='2001.0')
        data.append(form.Used_since.data=='2002.0')
        data.append(form.Used_since.data=='2003.0')
        data.append(form.Used_since.data=='2004.0')
        data.append(form.Used_since.data=='2005.0')
        data.append(form.Used_since.data=='2006.0')
        data.append(form.Used_since.data=='2007.0')
        data.append(form.Used_since.data=='2008.0')
        data.append(form.Used_since.data=='2009.0')
        data.append(form.Used_since.data=='2010.0')
        data.append(form.Used_since.data=='2011.0')
        data.append(form.Used_since.data=='2012.0')
        data.append(form.Used_since.data=='2013.0')
        data.append(form.Used_since.data=='2014.0')
        data.append(form.Used_since.data=='2015.0')
        data.append(form.Used_since.data=='2016.0')
        data.append(form.Used_since.data=='2017.0')
        data.append(form.Used_since.data=='2018.0')
        data.append(form.Used_since.data=='2019.0')
        data.append(form.Used_since.data=='2020.0')
        data.append(form.Used_since.data=='2021.0')
        data.append(form.Used_since.data=='2022.0')



        data.append(form.Transmission.data=='DSG')
        data.append(form.Transmission.data=='automatic')
        data.append(form.Transmission.data=='manual')
        


        data.append(form.City.data=='6 October')
        data.append(form.City.data=='Abu Hummus')
        data.append(form.City.data=='Abu Kabir')
        data.append(form.City.data=='Abu Qir')
        data.append(form.City.data=='Agamy')
        data.append(form.City.data=='Ain Shams')
        data.append(form.City.data=='Al Shorouk')
        data.append(form.City.data=='Alexandria')
        data.append(form.City.data=='Amreya')
        data.append(form.City.data=='Ashmoun')
        data.append(form.City.data=='Aswan')
        data.append(form.City.data=='Asyut')
        data.append(form.City.data=='Banha')
        data.append(form.City.data=='Beheira')
        data.append(form.City.data=='Beni Suef')
        data.append(form.City.data=='Bilbeis')
        data.append(form.City.data=='Borg el arab')
        data.append(form.City.data=='Cairo')
        data.append(form.City.data=='Dakahlia')
        data.append(form.City.data=='Damanhur')
        data.append(form.City.data=='Damietta')
        data.append(form.City.data=='Dikirnis')
        data.append(form.City.data=='Dokki')
        data.append(form.City.data=='Dyarb Negm')
        data.append(form.City.data=='Edku')
        data.append(form.City.data=='El Bagour')
        data.append(form.City.data=='El Gamaleya')
        data.append(form.City.data=='El Gouna')
        data.append(form.City.data=='El Haram')
        data.append(form.City.data=='El Katameya')
        data.append(form.City.data=='El Mahalla')
        data.append(form.City.data=='El Manial')
        data.append(form.City.data=='El Marg')
        data.append(form.City.data=='El Minya')
        data.append(form.City.data=='El Qanater El Khayreya')
        data.append(form.City.data=='El Salam City')
        data.append(form.City.data=='El Senbellawein')
        data.append(form.City.data=='El Wadi El Gedid')
        data.append(form.City.data=='El-Alamein')
        data.append(form.City.data=='El-Arish')
        data.append(form.City.data=='Faiyum')
        data.append(form.City.data=='Faqous')
        data.append(form.City.data=='Gharbia')
        data.append(form.City.data=='Giza')
        data.append(form.City.data=='Heliopolis')
        data.append(form.City.data=='Helwan')
        data.append(form.City.data=='Hurghada')
        data.append(form.City.data=='Imbaba')
        data.append(form.City.data=='Ismailia')
        data.append(form.City.data=='Kafr El Zayat')
        data.append(form.City.data=='Kafr Shukr')
        data.append(form.City.data=='Kafr el-Dawwar')
        data.append(form.City.data=='Kafr el-Sheikh')
        data.append(form.City.data=='Kerdasa')

        data.append(form.City.data=='Khanka')
        data.append(form.City.data=='Kom Hamada')
        data.append(form.City.data=='Kom Ombo')
        data.append(form.City.data=='Luxor')
        data.append(form.City.data=='Maadi')
        data.append(form.City.data=='Madinaty')
        data.append(form.City.data=='Mansoura')
        data.append(form.City.data=='Marsa Alam	')
        data.append(form.City.data=='Marsa Matrouh')
        data.append(form.City.data=='Minya Al Qamh')
        data.append(form.City.data=='Mit Ghamr')
        data.append(form.City.data=='Mohandessin')
        data.append(form.City.data=='Mokattam')
        data.append(form.City.data=='Monufia')
        data.append(form.City.data=='Nasr city')
        data.append(form.City.data=='New Administrative Capital	')
        data.append(form.City.data=='Obour City')
        data.append(form.City.data=='Port Said')
        data.append(form.City.data=='Qalyub')
        data.append(form.City.data=='Qalyubia')
        data.append(form.City.data=='Qena')
        data.append(form.City.data=='Quesna')
        data.append(form.City.data=='Ras Gharib')
        data.append(form.City.data=='Red Sea')
        data.append(form.City.data=='Rosetta')
        data.append(form.City.data=='Sadat City	')
        data.append(form.City.data=='Safaga')
        data.append(form.City.data=='Saft El Laban')
        data.append(form.City.data=='Sharm el-Sheikh')
        data.append(form.City.data=='Sharqia')
        data.append(form.City.data=='Sheikh Zayed City')
        data.append(form.City.data=='Sheraton')
        data.append(form.City.data=='Shibin El Qanater')
        data.append(form.City.data=='Shibin el Kom')
        data.append(form.City.data=='Shobra')
        data.append(form.City.data=='Sohag')
        data.append(form.City.data=='Suez')
        data.append(form.City.data=='Tagamo3 - New Cairo')
        data.append(form.City.data=='Tala')
        data.append(form.City.data=='Tanta')
        data.append(form.City.data=='Touhk')
        data.append(form.City.data=='Warraq')
        data.append(form.City.data=='Zagazig')
        data.append(form.City.data=='Zamalek')
        data.append(form.City.data=='Zefta')
        




        data.append(form.Color.data=='Silver')
        data.append(form.Color.data=='Black')
        data.append(form.Color.data=='White')
        data.append(form.Color.data=='Red')
        data.append(form.Color.data=='Gray')
        data.append(form.Color.data=='Dark red')
        data.append(form.Color.data=='Blue')
        data.append(form.Color.data=='Light grey')
        data.append(form.Color.data=='Dark blue')
        data.append(form.Color.data=='Gold')
        data.append(form.Color.data=='Green')
        data.append(form.Color.data=='Cyan')
        data.append(form.Color.data=='Mocha')
        data.append(form.Color.data=='Petroleum')
        data.append(form.Color.data=='Dark green')
        data.append(form.Color.data=='Brown')
        data.append(form.Color.data=='Olive')
        data.append(form.Color.data=='Champagne')
        data.append(form.Color.data=='Bronze')
        data.append(form.Color.data=='Beige')
        data.append(form.Color.data=='Yellow')
        data.append(form.Color.data=='Eggplant')
        data.append(form.Color.data=='Orange')
        data.append(form.Color.data=='Purple')


        data.append(form.Fuel.data=='gas')
        data.append(form.Fuel.data=='natural gas')
        data.append(form.Fuel.data=='diesel')
        data.append(form.Fuel.data=='Hybrid')
        data.append(form.Fuel.data=='Electric')

      
        scaler=joblib.load("models/scaler.pkl")
        scaled_data=scaler.transform([data])
        
        model=joblib.load("models/model.pkl")
        predict=model.predict(scaled_data)
        #return str(len(data))
        return render_template('thanks.html',predict=predict)
        #return redirect(url_for('thanks'),predict=predict)
 

    return render_template('index.html', form=form)

@app.route('/thanks')
def thanks():
    return render_template('thanks.html')

@app.route('/about')
def about():
    return render_template('about.html')

@app.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'),404    





if __name__=="__main__" :
    app.run(debug=True)   








 
 




 



 



 